kind: pipeline
type: docker
name: default

steps:
- name: dependencies
  image: node
  commands:
    - yarn
    - yarn global add @quasar/cli
  
- name: build
  image: node
  commands:
    - quasar build

- name: public
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: dist/spa/