kind: pipeline
type: docker
name: Publish Website

steps:
- name: Install Dependencies and Build
  image: node
  commands:
    - yarn
    - yarn global add @quasar/cli
    - quasar build

- name: Publish Website
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: dist/spa/